spring.application.name=talkivo

server.port=${PORT:8080}

tts.text.max-length=1000

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}

app.audio.storage-dir=${APP_AUDIO_STORAGE_DIR:./generated-audio}

piper.python-path=${PIPER_PYTHON_PATH:python}

piper.models-dir=${PIPER_MODELS_DIR:../piper/models}